name: Deploy Storybook to GitHub Pages

on:
  push:
    branches:
      - main # Or 'master' based on default branch

permissions:
  contents: write # 🔐 Required for GITHUB_TOKEN to push to gh-pages

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install dependencies
        run: npm ci # clean, fast, and consistent installs in continuous integration (CI) environments

      - name: Build Storybook
        run: npm run build-storybook

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./storybook-static
